; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_f103rb]
platform = ststm32
; board = genericSTM32F103R6
board = nucleo_f103rb
; framework = arduino
framework = cmsis
; framework = stm32cube

build_type = debug

# -----------------------------------------------------------------
# 시리얼 모니터 관련 직접 설정 구역
# -----------------------------------------------------------------
# 모니터링할 포트를 COM5로 강제 지정
monitor_port = COM5

# 통신 속도 지정 (앞서 터미널이 9600이었으므로 9600 지정, printf 연동 시 115200 권장)
monitor_speed = 115200

